title: Harrison Dandridge
description: Portfolio and Projects
remote_theme: pages-themes/slate

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  #- title: "Web Mapping and GIS" COMMENTED OUT FOR GENERAL PORTFOLIO USE
  # url: /WebMappingAndGIS COMMENTED OUT FOR GENERAL PORTFOLIO USE
  - title: "Contact"
    url: /contact

# Optional extras
search_enabled: true
