title: Harrison Dandridge
description: Portfolio and Projects
remote_theme: pages-themes/midnight

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Web Mapping and GIS"
    url: /WebMappingAndGIS
  - title: "Contact"
    url: /contact

# Optional extras
color_scheme: dark
logo: /assets/logo.png
search_enabled: true
